# ===== DEV 환경 =====

# API Base
api.base-url=https://api.dify.ai
api.auth.token=Bearer API_KEY_HERE

# File Upload
# POST {base-url}/v1/files/upload
# Headers: Authorization, Content-Type: multipart/form-data
# Body(form-data): file(file), user, conversation_id
api.upload.path=/v1/files/upload
api.user=LogAnalyzer

# Chat with Files
# POST {base-url}/v1/chat-messages
# Headers: Authorization, Content-Type: application/json
api.chat.path=/v1/chat-messages
api.chat.response-mode=blocking
