# ===== DEV 환경 =====

# API Base
api.base-url=https://api.dify.ai
api.auth.suspected=Bearer app-YourSuspectedToken
api.auth.anomaly=Bearer app-YourAnomalyToken
api.auth.insights=Bearer app-YourInsightsToken

# File Upload
# POST {base-url}/v1/files/upload
# Headers: Authorization, Content-Type: multipart/form-data
# Body(form-data): file(file), user, conversation_id
api.upload.path=/v1/files/upload
api.user=LogAnalyzer

# Chat with Files
# POST {base-url}/v1/chat-messages
# Headers: Authorization, Content-Type: application/json
api.chat.path=/v1/chat-messages
api.chat.response-mode=blocking


# MAKE EXE Files
# mvn javafx:jlink
# jpackage --type app-image --name LogAnalyzer --app-version 1.0.0 --runtime-image target/hellofx --module hellofx/org.openjfx.hellofx.App --dest target/dist --java-options '-Dapp.dir=$APPDIR'
# copy src\main\resources\application-dev.properties target\dist\LogAnalyzer\