# ===== PROD 환경 =====

# API Base
api.base-url=https://builder.ais-p.shinhands.co.kr
api.auth.token=Bearer app-hqw4h6Dfrwt7ufDTXp5BL2i3

# File Upload
# POST {base-url}/v1/files/upload
# Headers: Authorization, Content-Type: multipart/form-data
# Body(form-data): file(file), user, conversation_id
api.upload.path=/v1/files/upload
api.user=test

# Chat with Files
# POST {base-url}/v1/chat-messages
# Headers: Authorization, Content-Type: application/json
api.chat.path=/v1/chat-messages
api.chat.response-mode=blocking
